#pragma once
#include <windows.h>
#include <wrl.h>
#include <shellapi.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <D3Dcompiler.h>
#include "dxcapi.h"
#include <cstdint>
#include <array>
#include <string>
#include <vector>
#include <mutex>
#include <optional>
#include "DXTex/DirectXTex.h"
#include "SimpleMath/SimpleMath.h"
#include "Helper.h"
#include "Definition.h"
#include "D3dx12.h"
#include "D3D12MemoryAllocator/D3D12MemAlloc.h"
#include <numeric>
